### PR TITLE
Separate Writeup Log By Channel

### PR DESCRIPTION
**Pull request by SupianIDz**
Untuk memudahkan maintain kedepannya.

1. Saya menyarankan logika writeup terpisah, dibandingkan logika ditulis pada middleware.
2. Setiap Log dipisah berdasarkan jenisnya dibanding semaunya menjadi satu didalam laravel local log (laravel.log), ini menyabkan sulitnya membedakan mana writeup request, response, query dan dari log Laravel lainya dan ini untuk memudahkan pembacaan log pengguna nantinya.

Berikut draftnya.

### CODE REVIEW

**Comment by SupianIDz** [comment]
DB listener tidak berfungsi sebagaimana mestinya ketika ditulis diluar dari boot service provider, namun berfungsi dengan baik ketika didalam.

Ada saran ?

**Comment by abdurrahmanriyad** [comment]
@SupianIDz Not understand what you said.
Can you please write in English?

**Comment by SupianIDz** [comment]
Oh, sorry. I thought you were Indonesian, because there are similarities in names.

To facilitate future code maintenance.

1. I suggest separate writeup logic, rather than logic written on the middleware.

2. Each log is separated by type rather than all being one in the local laravel log (laravel.log), this makes it difficult to distinguish between writeup requests, responses, queries and other Laravel logs and this is to facilitate reading user logs later.

**Comment by SupianIDz** [comment]
My draft is still having trouble with the DB listener that doesn't work properly when written outside of the service provider `boot`, but works fine when it's in `boot`.

Any suggestion ?

**Comment by abdurrahmanriyad** [comment]
> Oh, sorry. I thought you were Indonesian, because there are similarities in names.
> 
> To facilitate future code maintenance.
> 
> 1. I suggest separate writeup logic, rather than logic written on the middleware.
> 2. Each log is separated by type rather than all being one in the local laravel log (laravel.log), this makes it difficult to distinguish between writeup requests, responses, queries and other Laravel logs and this is to facilitate reading user logs later.

I welcome any good change that would improve the codebase.
Please make your changes and hit a PR. If it goes well I will merge

**Comment by abdurrahmanriyad** [comment]
> My draft is still having trouble with the DB listener that doesn't work properly when written outside of the service provider `boot`, but works fine when it's in `boot`.
> 
> Any suggestion ?

This because boot method is called upon all other service providers are registered.
Also, this DB:listener suggested to put on service provider's boot method
https://laravel.com/docs/8.x/database#listening-for-query-events

**Comment by SupianIDz** [comment]
> > My draft is still having trouble with the DB listener that doesn't work properly when written outside of the service provider `boot`, but works fine when it's in `boot`.
> > Any suggestion ?
> 
> This because boot method is called upon all other service providers are registered.
> Also, this DB:listener suggested to put on service provider's boot method
> https://laravel.com/docs/8.x/database#listening-for-query-events

Okay, wait a minutes.

**Comment by SupianIDz** [comment]
@abdurrahmanriyad  Can you help me deal with this little conflict? Because I've turned off the computer, get ready to sleep.

**Comment by SupianIDz** [comment]
@abdurrahmanriyad ready for review and merger. I suggest this to version 2.x

**Pull request closed without merging**
